# Generated by Django 5.0.2 on 2024-03-06 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_tags_tag_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='question_tags', to='polls.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='polls.question'),
        ),
    ]
